### ISSUE TITLE
Drop Classes Description

### ISSUE THREAD

**Issue by betsay27** [Team-Runtime-Error/CSCI4060-Fall2020-Advising-Project#11]
Create a use case description for Drop Classes.

**Comment by btreno** [comment]
Step 3 lacks detail about how we will check prerequisites, because we don't know the details of our access to the course list

**Comment by null-86** [comment]
Made an early draft. I haven't revised it to the point that it's ready for group review, so I'm moving it to Testing. I've uploaded the rough draft.

**Comment by null-86** [comment]
I've double checked the draft, and it's ready for group review.

**Comment by null-86** [comment]
Group reviewed version 1 and agreed to move to closed
