### ISSUE TITLE
Server-Side Connection

### ISSUE THREAD

**Issue by looseZeus** [Team-Runtime-Error/CSCI4060-Fall2020-Advising-Project#22]

**Comment by looseZeus** [comment]
- Connected server code with database
- Compared my 'dummy user values' with the present database user values
- Log to console whether the dummy values are valid/invalid
- Currently trying to find out where the user input values(from the login) are stored, so I can push them to server code and do the 
   validation.

-if anyone can trace where entered username/password are stored in /client/src/pages/login.tsx, please get in touch with me

**Comment by looseZeus** [comment]
Working on Building rest APIs for different types of requests from the client.

**Comment by looseZeus** [comment]
Finished writing api for
- checking to see if user is registered or not
- to see all available registered users
Now the client app needs to use these api and can verify the user or extract total users in db.

what other interactions do I need to consider? 
From the client side what are we storing into the DB?

**Comment by betsay27** [comment]
We can make a sample table that allows the advisor to store a students info. It shouldnt be too hard, but we gotta wait til the advisor page is done. Or we could use the Home page we have now to store anything into a sample table. Its up to us @Bijaypoudel @lawrenceobioma I'm closing this issue and making another.

**Comment by looseZeus** [comment]
Yeah sure we can do either. Was anyone able to fetch from the api routes?

**Comment by betsay27** [comment]
I havent been able to work on it because I don't have your code, but it shouldn't take me too long @Bijaypoudel

**Comment by looseZeus** [comment]
I merged it into a different branch.
