### ISSUE TITLE
Hash Passwords in DB

### ISSUE THREAD

**Issue by betsay27** [Team-Runtime-Error/CSCI4060-Fall2020-Advising-Project#29]
We need to encrypt our passwords in our database somehow. Preferably by hashing them with BCrypt (?) or local passport (?). To be discussed by the team.

**Comment by looseZeus** [comment]
Currently testing bcrypt

**Comment by looseZeus** [comment]
Hashing into db -done

**Comment by looseZeus** [comment]
Authenticating user using the hash - done
