### ISSUE TITLE
EC2 to RDS Connection

### ISSUE THREAD

**Issue by betsay27** [Team-Runtime-Error/CSCI4060-Fall2020-Advising-Project#4]
*explanation*

**Comment by null-86** [comment]
Setup EC2 and RDS instances on AWS
(details to login to each will be included in the discord)

**Comment by null-86** [comment]
moving this to testing until others can confirm they have successfully signed on

**Comment by lawrenceobioma** [comment]
Yes that’s fine. We also need to have that set up and put a table in there with some info so we can have that ready to connect with the front-end side of things. I need to figure out how we connect it haha

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by null-86** [comment]
Built simple js program which allows us to store and retrieve data from the database. it's called test.js and is located in the github and discord channels.

edit: i removed the password, username, etc from the github version for security reasons
