### ISSUE TITLE
Revise Use Case Diagram

### ISSUE THREAD

**Issue by betsay27** [Team-Runtime-Error/CSCI4060-Fall2020-Advising-Project#5]
Use cases:
  - our looks "steppy"
  - display needs to be linked to update schedule
  - remove view courses??
  - we NEED an admin actor that can update major requirements, add courses, and update advisor/student lists
  - the flow should be view courses -> update -> view -> accept
- suggest classes to the student
- show what classes are available in the upcoming semester

**Comment by looseZeus** [comment]
Found out 'The director of advising' hand-matches advisors and advisees based on students major, available advisors' schedule and each advisor's current load(advisees). And finally the major department comes to a conclusion. I found this from a non-ULM university. Couldn't find any info on ULM's website.

**Comment by betsay27** [comment]
Use case diagram completed on 8/26/2020. Version 1.0.
