### ISSUE TITLE
Set Schedule Page(class/class schedule)

### ISSUE THREAD

**Issue by looseZeus** [Team-Runtime-Error/CSCI4060-Fall2020-Advising-Project#51]

**Comment by null-86** [comment]
We might be able to add this flag - showHeaderBar={false}  - in the ScheduleComponent tag to completely remove the header. The header can also be manually edited according to the docs https://ej2.syncfusion.com/react/documentation/schedule/header-bar/

We can remove Sunday and Saturday by changing  option="Week" to option="WorkWeek"

We can remove the numbers according to the docs by using the OnRenderCell method according to this page of the docs https://ej2.syncfusion.com/react/documentation/schedule/header-bar/

**Comment by null-86** [comment]
we can add custom headers using the HeaderRowsDirective and HeaderRowDirective according to https://ej2.syncfusion.com/react/documentation/schedule/header-rows/

**Comment by lawrenceobioma** [comment]
All that is left is to create a way to load the schedule to the UI based on the login CWID. Aside from that, this is ready for the alpha demo.
