### ISSUE TITLE
Hashing Bug

### ISSUE THREAD

**Issue by betsay27** [Team-Runtime-Error/CSCI4060-Fall2020-Advising-Project#57]
This is kinda complicated so I'll try to explain: 
Only users being added through the Login.js page will have their passwords hashed.
- we want all passwords to be hashed
- we aren't using the "create user" in our final demo so the hashing needs to be moved to passwords already in the database and/or passwords added manually to the database
The hashing issue is causing our Login.tsx auth to fail because it's trying to compare unhashed passwords (in the DB) to the submitted hashed passwords (/authUser).

**Comment by looseZeus** [comment]
"the hashing needs to be moved to passwords already in the database and/or passwords added manually to the database"
I'm not sure if I understand this. 

"passwords added manually to the database" By this, do you mean using MySQL query(client-side independent)?
