### ISSUE TITLE
Make a Cookie to Store User Object

### ISSUE THREAD

**Issue by betsay27** [Team-Runtime-Error/CSCI4060-Fall2020-Advising-Project#63]
We need to make a cookie on our server that stores the current user object. Look into JWT, Cookies, and Tokens.

**Comment by null-86** [comment]
We have the ability to get, set and remove cookies as well as checking whether they exist. We're now working on implementing them into the App routing. We're looking for a way to check cookies synchronously before routing the user.

**Comment by betsay27** [comment]
Cookies are storing our user object.
