### ISSUE TITLE
Add Calendar to Appt Page

### ISSUE THREAD

**Issue by betsay27** [Team-Runtime-Error/CSCI4060-Fall2020-Advising-Project#68]

**Comment by betsay27** [comment]
Decided to use Outlook API. All ULM students/faculty have an Outlook account (that automatically contains the Microsoft calendar) so this should be migratable and last as long as ULM uses Outlook.

**Comment by null-86** [comment]
Betsy and I looked into implementing the api. Right now we can display the events, but we cannot add events.

**Comment by null-86** [comment]
Internet is out, so I haven't and won't been able to update for a bit. I've made a very barebones appt page for student and advisor (one each). Once I'm back online, I will test and merge it

**Comment by null-86** [comment]
After a lifetime's worth of debugging, I think the code is ready to go. It contains all of the backed code to insert, delete, and update appointments for both the advisor and the student as well as the front end api to interface with those commands. The pages themselves (one for student and one for advisor) are rudimentary, but they work. We still need a calendar view for them.
